apiVersion: apps/v1
kind: Deployment # deployment object
metadata:
  name: backend-deployment # name of the deployment
  labels:
    app: backend
spec: # specification of the deployment
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: klerith/k8s-teslo-backend:1.1.0
        ports:
        - containerPort: 3000
        env:
        - name:  APP_VERSION
          value: "1.1.0"
        - name:  PORT
          value: "3000"
        - name:  STAGE
          value: "prod"
        - name:  DB_NAME
          valueFrom: # value from secret
            configMapKeyRef:
              name: postgres-config # name of the secret
              key: DB_NAME
        - name:  DB_HOST
          valueFrom: # value from secret
            configMapKeyRef:
              name: postgres-config # name of the secret
              key: DB_HOST
        - name:  DB_PORT
          valueFrom: # value from secret
            configMapKeyRef:
              name: postgres-config # name of the secret
              key: DB_PORT
        - name:  DB_USERNAME
          valueFrom: # value from secret
            secretKeyRef:
              name: postgres-secret # name of the secret
              key: DB_USER
        - name:  DB_PASSWORD
          valueFrom: # value from secret
            secretKeyRef:
              name: postgres-secret # name of the secret
              key: DB_PASSWORD
        - name:  JWT_SECRET
          valueFrom: # value from secret
            secretKeyRef:
              name: backend-secrets # name of the secret
              key: JWT_SECRET
--- # separate the two objects with three dashes
apiVersion: v1
kind: Service # service object
metadata:
  name: backend-service # name of the service
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 3000 # port of the service - can be any port
      targetPort: 3000 # port of the container
      nodePort: 30300