apiVersion: apps/v1
kind: Deployment # deployment object
metadata:
  name: pg-deployment # name of the deployment
  labels:
    app: pg-admin
spec: # specification of the deployment
  replicas: 1
  selector:
    matchLabels:
      app: pg-admin
  template:
    metadata:
      labels:
        app: pg-admin
    spec:
      containers:
      - name: pg-admin
        image: dpage/pgadmin4:6.17
        ports:
        - containerPort: 80
        env:
        - name:  PGADMIN_DEFAULT_PASSWORD
          valueFrom: # value from secret
            secretKeyRef:
              name: pg-admin-secrets # name of the secret
              key: PG_USER_PASSWORD
        - name:  PGADMIN_DEFAULT_EMAIL
          valueFrom: # value from secret
            secretKeyRef:
              name: pg-admin-secrets # name of the secret
              key: PG_USER_EMAIL
        - name:  PGADMIN_ENHANCED_COOKIE_PROTECTION
          value: "false"
--- # separate the two objects with three dashes
apiVersion: v1
kind: Service # service object
metadata:
  name: pg-service # name of the service
spec:
  type: NodePort
  selector:
    app: pg-admin
  ports:
    - protocol: TCP
      port: 80 # port of the service - can be any port
      targetPort: 80 # port of the container
      nodePort: 30200