apiVersion: v1
kind: Secret # secret object
metadata:
  name: postgres-secret # name of the secret
type: Opaque # type of the secret
data:
  DB_USER: cG9zdGdyZXM= # postgres
  DB_PASSWORD: cG9zdGdyZXM= # postgres